ALTER TABLE consultant_profile
    ADD COLUMN IF NOT EXISTS vehicle_type VARCHAR(20) DEFAULT 'CAR',
    ADD COLUMN IF NOT EXISTS fiscal_power INT DEFAULT 7,
    ADD COLUMN IF NOT EXISTS km_annual INT DEFAULT 4999;
