apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: multi-agent
type: Opaque
stringData:
  OPENAI_API_KEY: $OPENAI_API_KEY
  OPENAI_LLM_API_KEY: $OPENAI_LLM_API_KEY
  AI_CORE_ADMIN_KEY: $AI_CORE_ADMIN_KEY
  KEYCLOAK_ADMIN_USER: $KEYCLOAK_ADMIN_USER
  KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
  MAIL_USERNAME: $MAIL_USERNAME
  MAIL_PASSWORD: $MAIL_PASSWORD
  MAIL_FROM: $MAIL_FROM
